/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SandboxImport } from './routes/sandbox'
import { Route as ProfileImport } from './routes/profile'
import { Route as NewsImport } from './routes/news'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SandboxRoute = SandboxImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const NewsRoute = NewsImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/sandbox': typeof SandboxRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/sandbox': typeof SandboxRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/sandbox': typeof SandboxRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/news' | '/profile' | '/sandbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/news' | '/profile' | '/sandbox'
  id: '__root__' | '/' | '/news' | '/profile' | '/sandbox'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  SandboxRoute: typeof SandboxRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  SandboxRoute: SandboxRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/news",
        "/profile",
        "/sandbox"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/news": {
      "filePath": "news.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/sandbox": {
      "filePath": "sandbox.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
